/**
 * MIDI Control Change (CC) Konstanten
 * Mapping von CC-Nummern zu lesbaren Namen
 */
export const cc = {
  0: 'Bank Sel.',
  1: 'Mod. Wheel',
  2: 'Breath Contr.',
  3: 'Undefined',
  4: 'Foot Contr.',
  5: 'Portamento',
  6: 'Data Entry',
  7: 'Channel Vol.',
  8: 'Balance',
  9: 'Undefined',
  10: 'Pan',
  11: 'ExpressionContr.',
  12: 'Effect Control 1',
  13: 'Effect Control 2',
  14: 'Undefined',
  16: 'General PurposeContr. 1',
  17: 'General PurposeContr. 2',
  18: 'General PurposeContr. 3',
  19: 'General PurposeContr. 4',
  20: 'Undefined',
  21: 'Undefined',
  22: 'Undefined',
  23: 'Undefined',
  24: 'Undefined',
  25: 'Undefined',
  26: 'Undefined',
  27: 'Undefined',
  28: 'Undefined',
  29: 'Undefined',
  30: 'Undefined',
  31: 'Undefined',
  32: 'Bank Select',
  33: 'Modulation Wheel',
  34: 'BreathContr.',
  35: 'Undefined',
  36: 'FootContr.',
  37: 'Portamento Time',
  38: 'Data Entry',
  39: 'Channel Volume',
  40: 'Balance',
  41: 'Undefined',
  42: 'Pan',
  43: 'ExpressionContr.',
  44: 'Effect control 1',
  45: 'Effect control 2',
  46: 'Undefined',
  47: 'Undefined',
  48: 'General PurposeContr. 1',
  49: 'General PurposeContr. 2',
  50: 'General PurposeContr. 3',
  51: 'General PurposeContr. 4',
  52: 'Undefined',
  53: 'Undefined',
  54: 'Undefined',
  55: 'Undefined',
  56: 'Undefined',
  57: 'Undefined',
  58: 'Undefined',
  59: 'Undefined',
  60: 'Undefined',
  61: 'Undefined',
  62: 'Undefined',
  63: 'Undefined',
  64: 'Damper Pedal',
  65: 'Portamento',
  66: 'Sostenuto',
  67: 'Soft Pedal',
  68: 'Legato',
  69: 'Hold 2',
  70: 'Sound Variation',
  71: 'Filter Resonance',
  72: 'Release Time',
  73: 'Attack Time',
  74: 'Brightness',
  75: 'Decay Time',
  76: 'Vibrato Rate',
  77: 'Vibrato Depth',
  78: 'Vibrato Delay',
  79: 'SoundContr. 10',
  80: 'General PurposeContr. 5',
  81: 'General PurposeContr. 6',
  82: 'General PurposeContr. 7',
  83: 'General PurposeContr. 8',
  84: 'Portamento Control',
  85: 'Undefined',
  86: 'Undefined',
  87: 'Undefined',
  88: 'High Resolution Velocity Prefix',
  89: 'Undefined',
  90: 'Undefined',
  91: 'Effects 1 Depth',
  92: 'Effects 2 Depth',
  93: 'Effects 3 Depth',
  94: 'Effects 4 Depth',
  95: 'Effects 5 Depth',
  96: 'Data Increment',
  97: 'Data Decrement',
  98: 'Non-Registered Parameter Number',
  99: 'Non-Registered Parameter Number',
  100: 'Registered Parameter Number',
  101: 'Registered Parameter Number',
  102: 'Undefined',
  103: 'Undefined',
  104: 'Undefined',
  105: 'Undefined',
  106: 'Undefined',
  107: 'Undefined',
  108: 'Undefined',
  109: 'Undefined',
  110: 'Undefined',
  111: 'Undefined',
  112: 'Undefined',
  113: 'Undefined',
  114: 'Undefined',
  115: 'Undefined',
  116: 'Undefined',
  117: 'Undefined',
  118: 'Undefined',
  119: 'Undefined',
  120: 'All Sound Off',
  121: 'Reset All Controllers',
  122: 'Local Control On/Off',
  123: 'All Notes Off',
  124: 'Omni Mode Off',
  125: 'Omni Mode On',
  126: 'Mono Mode On',
  127: 'Poly Mode On',
};

/**
 * MIDI System Messages (≥240)
 */
export const cc2 = {
  241: 'MIDI Time Code',
  242: 'Song Position',
  243: 'Song Select',
  244: 'Undefined',
  245: 'Undefined',
  246: 'Tune request',
  248: 'Timing clock',
  249: 'Undefined',
  250: 'Start',
  251: 'Continue',
  252: 'Stop',
  253: 'Undefined',
  254: 'Active Sensing',
  255: 'Reset',
};

/**
 * MIDI Message Types (Status-Byte oberes Nibble)
 */
export const mmsg = {
  8: 'Note Off',
  9: 'Note On',
  10: 'Aftertouch',
  11: 'CC',
  12: 'Program Change',
  13: 'Ch. Aftertouch',
  14: 'Pitch Wheel',
};

/**
 * Notennamen (Chromatische Skala)
 */
export const notes = ['C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B'];

/**
 * MIDI System Messages (Status-Bytes)
 * MIDI_SYSEX_START markiert die Grenze zwischen Channel Messages (128-239) und System Messages (240-255)
 */
export const MIDI_SYSEX_START = 0xf0; // 240 - SysEx Start / Grenze zu System Messages
export const MIDI_SYSEX_END = 0xf7; // 247 - SysEx End (EOX)
export const MIDI_TIMING_CLOCK = 0xf8; // 248 - Timing Clock
export const MIDI_ACTIVE_SENSING = 0xfe; // 254 - Active Sensing
